version: '3'
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
   # image: node:20.10.0-bullseye-slim
    tty: true
    volumes:
      - .:/home/node/app:cached
      - /home/node/app/node_modules
    ports:
      - "5173:5173"